# Generated by Django 3.2.6 on 2021-08-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('body', models.TextField(verbose_name='Описание')),
                ('isChecked', models.BooleanField(default=False, verbose_name='Выполнено?')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Позиция')),
            ],
        ),
    ]
